apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-application
  namespace: kavyaargo
spec:
  project: default
  source:
    repoURL: 'https://github.com/Kavyareddivari9/kavya-argo'
    path: 'argo-helm'
    targetRevision: 'main'
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'kavyaargo'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
